### ISSUE TITLE
What does `topic_num` took as 175 represent?

### ISSUE THREAD

**Issue by PalgunaGopireddy** [Alien9427/XAI4SAR-PGIL#5]
I know the `cate_num` sent as `ResNet18_PGIL(config['cate_num'])`  to create `model_CNN` represents the number of target classes.

But I don't understand how to decide the value of `topic_num` sent as ResNet18_PGN(config['topic_num'])` to create `model_CompNet`.

What does `topic_num` represent?

**Comment by Alien9427** [comment]
Please refer to Equation (5) in the paper, where the topic_num denotes K in this equation.

**Comment by Alien9427** [comment]
@PalgunaGopireddy

**Comment by PalgunaGopireddy** [comment]
Thank you @Alien9427
